### ISSUE TITLE
springboot微信公众号支付

### ISSUE THREAD

**Issue by cjcj125125** [werhero/WeChatPay#1]
大佬你好，看了你的代码解决了一些问题，然而还有一个问题没有解决，我的后台是前后端分离的，我们的业务需求是直接扫码就进入支付页面，而公众号支付需要获取openid，我获取openid的这个步骤应该放到哪里？？希望大佬留个qq，可以向大佬请教，谢谢

**Comment by werhero** [comment]
抱歉，很久没登陆了！
这里触发支付页面的场景是用户主动申请支付，业务过程中需要用户授权，授权后即可获得openid，
但是你说的是扫码支付，这里没有涉及到，请查阅官方文档
